#!/usr/bin/env bash
# Sync the manager ClusterRole rules from controller-gen output into the Helm
# chart template.  Merges the generated rules with any Helm-only extras from
# charts/operator/clusterrole-extra-rules.yaml.
#
# Usage: hack/chart-sync-rbac.sh [CHART_DIR]
#   CHART_DIR defaults to charts/operator

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHART_DIR="${1:-${REPO_ROOT}/charts/operator}"

GENERATED="${REPO_ROOT}/config/rbac/role.yaml"
EXTRAS="${CHART_DIR}/clusterrole-extra-rules.yaml"
TARGET="${CHART_DIR}/templates/clusterrole.yaml"

if ! command -v yq &>/dev/null; then
  echo "ERROR: yq (https://github.com/mikefarah/yq) is required but not found in PATH" >&2
  exit 1
fi

if [[ ! -f "${GENERATED}" ]]; then
  echo "ERROR: ${GENERATED} not found — run 'make manifests' first" >&2
  exit 1
fi

generated_rules="$(yq -I 4 -P '.rules' "${GENERATED}")"

if [[ -z "${generated_rules}" || "${generated_rules}" == "null" ]]; then
  echo "ERROR: No rules found in ${GENERATED}" >&2
  exit 1
fi

cat > "${TARGET}" <<'HELM_HEADER'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "workbenches-operator.managerClusterRoleName" . }}
  labels:
    {{- include "workbenches-operator.labels" . | nindent 4 }}
rules:
HELM_HEADER

echo "${generated_rules}" | sed 's/^/  /' >> "${TARGET}"

if [[ -f "${EXTRAS}" ]]; then
  extra_rules="$(yq -I 4 -P '... comments=""' "${EXTRAS}")"
  if [[ -n "${extra_rules}" ]]; then
    {
      echo "  # Helm-only rules (not generated by controller-gen)."
      echo "${extra_rules}" | sed 's/^/  /'
    } >> "${TARGET}"
  fi
fi

echo "Synced ClusterRole rules into ${TARGET}"
